* Problem A. Mushroom Monster


** Problem

_Kaylin_ loves mushrooms. 

Put them on her plate and she'll eat them up! 

In this problem she's eating  _a plate of mushrooms_, and  _Bartholomew_  is  _putting more pieces on her plate_ 

In this problem, we'll look at  _how many pieces of mushroom are on her plate at 10-second intervals_ 

_Bartholomew_  could put any  _non-negative_ integer number of mushroom pieces down  _at any time_, 
and  _the only way they can leave the plate is by being eaten_ 

_Figure out the minimum number of mushrooms_ that  _Kaylin_   _could have eaten_  using two different methods of computation: 

        1. Assume  _Kaylin_  could eat  _any number_  of mushroom pieces  _at any time_ 

	2. Assume that, starting with  _the first time we look at the plate_  
	   _Kaylin_  eats mushrooms at a  _constant rate_  whenever there are mushrooms on her plate. 


For example, if the input is 10 5 15 5: 

With the  _first method_,  _Kaylin_  must have eaten  _at least 15_  mushroom pieces: 

	first she eats 5, 
	then 10 more are put on her plate, 
	then she eats another 10. 
	There's no way she could have eaten fewer pieces. 

With the  _second method_, _Kaylin_  must have eaten  _at least 25_  mushroom pieces. 

	We can determine that she must eat mushrooms at a rate of  _at least 1 piece per second_ 
	She starts with 10 pieces on her plate. 
	In the first 10 seconds, she eats 10 pieces, 
	and 5 more are put on her plate. 
	In the next 5 seconds, she eats 5 pieces, then her plate stays empty for 5 seconds, 
	and then  _Bartholomew_  puts 15 more pieces on her plate. 
	Then she eats 10 pieces in the last 10 seconds. 



** Input

The first line of the input gives the number of test cases, T. T test cases follow. 

Each will consist of one line containing a single integer  _N_, 

followed by a line containing  _N_  space-separated integers  _mi_; 

the number of mushrooms on Kaylin's plate at the start, and at 10-second intervals. 


** Output

For each test case, output one line containing "Case #x: y z", 
where x is the test case number (starting from 1), 
	y is the minimum number of mushrooms Kaylin could have eaten using the  _first_   method of computation, 
	z is the minimum number of mushrooms Kaylin could have eaten using the  _second_  method of computation. 

** Limits

1 ≤ T ≤ 100.


*** Small dataset

2 ≤ N ≤ 10.
0 ≤ mi ≤ 100.

*** Large dataset

2 ≤ N ≤ 1000.
0 ≤ mi ≤ 10000.


** Sample


*** Input

4
4
10 5 15 5
2
100 100
8
81 81 81 81 81 81 81 0
6
23 90 40 0 100 9


*** Output

Case #1: 15 25
Case #2: 0 0
Case #3: 81 567
Case #4: 181 244




