* Problem D. Ominous Omino


** Problem

An  _N-omino_  is a two-dimensional shape formed by joining  _N_  unit cells 
fully along their edges in some way. 

a   _1-omino_  is a   _1x1_  unit square, 
an  _N-omino_  is an  _(N-1)_     omino with one or more of its 
edges joined to an adjacent 1x1 unit square. 

*** We consider two  _N-ominoes_  to be the  _same_  

if _one_ can be _transformed_ into the _other_  _via reflection_  _and/or_  _rotation_. 

For example, these are the five possible 4-ominoes:

...


And here are some of the 108 possible 7-ominoes:

...

*** _Richard_  and  _Gabriel_  are going to play a game with the following rules, 
for some predetermined values of _X_ , _R_ , and  _C_ :


**** 1. _Richard_ will choose  _any_  one of the possible  _X-ominoes_

**** 2. _Gabriel_ must use  _at least one copy of that X-omino_, along with 
arbitrarily many copies of any X-ominoes (which can include the one Richard chose), 
to completely  _fill_  in an _R-by-C_ grid. 

_Gabriel_  is allowed to  _rotate_  or  _reflect_  as many of the X-ominoes as he wants,
including the one Richard chose. 

**** If  _Gabriel_  can completely fill in the grid, he wins; otherwise, Richard wins.

Given particular values  _X, R, and C_  

*** can  _Richard_ choose an X-omino that will ensure that he wins, 
or is Gabriel guaranteed to win no matter what Richard chooses? 

** Input

The first line of the input gives the number of test cases, T. 

T lines follow. 

Each contains three space-separated integers: X, R, and C. 


** Output

For each test case, output one line containing "Case #x: y", 
where x is the test case number (starting from 1) and y is 
either RICHARD (if there is at least one choice that ensures 
victory for Richard) or GABRIEL (if Gabriel will win no matter 
what Richard chooses).

** Limits

*** Small dataset

T = 64.
1 ≤ X, R, C ≤ 4.

*** Large dataset

1 ≤ T ≤ 100.
1 ≤ X, R, C ≤ 20.

** Sample

*** Input

4
2 2 2
2 1 3
4 4 1
3 2 3

*** Output

Case #1: GABRIEL
Case #2: RICHARD
Case #3: RICHARD
Case #4: GABRIEL


In case #1, _Richard_ only has one 2-omino available to choose 
-- the 1x2 block formed by joining two unit cells together. 
No matter how Gabriel places this block in the 2x2 grid, he 
will leave a hole that can be exactly filled with another 1x2 
block. So Gabriel wins.

In case #2,  _Richard_  has to choose the 1x2 block, but no matter
 where Gabriel puts it, he will be left with a single 1x1 hole 
that he cannot fill using only 2-ominoes. So Richard wins.

In case #3, one winning strategy for  _Richard_  is to choose the 
2x2 square 4-omino. There is no way for Gabriel to fit that 
square into the 4x1 grid such that it is completely contained 
within the grid, so Richard wins.

In case #4, Richard can either pick the straight 3-omino or the 
L-shaped 3-omino. In either case, Gabriel can fit it into the grid 
and then use another copy of the same 3-omino to fill in the remaining hole.
