* Problem A. Standing Ovation


** Problem

It's opening night at the opera, and your friend is the prima donna (the lead female singer).
You will not be in the audience, but you want to make sure she receives a standing ovation --
 with every audience member standing up and clapping their hands for her.

*** Initially, the entire audience is seated. 

Everyone in the audience has a shyness level.

*** An audience member with shyness level  _Si_  will wait until  _at least_   _S_  other audience members
have already stood up to clap, and if so, she will immediately stand up and clap. 

**** If  _Si_   = 0,
then the audience member will always stand up and clap immediately, regardless of what anyone
else does. 

For example, an audience member with  _Si_  = 2 will be seated at the beginning, but
will stand up to clap later after she sees  _at least_  two other people standing and clapping.


*** You know the shyness level of everyone in the audience,

*** and you are prepared to  _invite additional_
friends of the prima donna to be in the audience to ensure that _everyone in the crowd stands up_
and claps in the end. 

_Each of these friends may have any shyness value that you wish_ , 
not necessarily the same. 

*** What is the  _minimum_  number of friends that you need to  _invite_  to 
guarantee a standing ovation?

** Input

The first line of the input gives the number of test cases, T. 
T test cases follow. 

Each consists of one line with  _Smax_ , the  _maximum shyness level_  of 
the shyest person in the audience, followed by a string of  _Smax + 1 single digits_ . 

The  _kth_  digit of this string (counting starting from _0_) represents 
_how many people in the audience have shyness level k_ . 

For example, the string "409" would mean that there were four audience members with Si = 0 and nine 
audience members with Si = 2 (and none with Si = 1 or any other value). 

Note that there will initially always be between  _0 and 9_  people with each shyness level.

The string will never end in a  _0_ . Note that this implies that  _there will always be at least one person in the audience_ .


** Output

For each test case, output one line containing "Case #x: y", where x is the test case number (starting from 1) and

y is the minimum number of friends you must invite.

** Limits


1 ≤ T ≤ 100.


*** Small dataset

0 ≤ Smax ≤ 6.

*** Large dataset

0 ≤ Smax ≤ 1000.


** Sample


*** Input

4
4 11111
1 09
5 110011
0 1


*** Output

Case #1: 0
Case #2: 1
Case #3: 2
Case #4: 0


In Case #1, the audience will eventually produce a standing ovation on its own,
without you needing to add anyone -- first the audience member with Si = 0 will
stand up, then the audience member with Si = 1 will stand up, etc.

In Case #2, a friend with Si = 0 must be invited, but that is enough to get the
entire audience to stand up.

In Case #3, one optimal solution is to add two audience members with Si = 2.

In Case #4, there is only one audience member and he will stand up immediately.
No friends need to be invited.


